force-app/main/default/objects/GenericGatewayLog__c/GenericGatewayLog__c.object-meta.xml
<CustomObject>
    <label>Generic Gateway Log</label>
    <nameField>
        <displayFormat>GE{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Gateway Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GenericGatewayLog__c/fields/InteractionType__c.field-meta.xml
<CustomField>
    <fullName>InteractionType__c</fullName>
    <label>Interaction Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LoyaltyTransaction__c/LoyaltyTransaction__c.object-meta.xml
<CustomObject>
    <label>Loyalty Transaction</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Loyalty ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LoyaltyTransaction__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Capture</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LoyaltyTransaction__c/fields/GatewaySentOn__c.field-meta.xml
<CustomField>
    <fullName>GatewaySentOn__c</fullName>
    <label>Gateway Sent On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LoyaltyTransaction__c/fields/GatewayStatus__c.field-meta.xml
<CustomField>
    <fullName>GatewayStatus__c</fullName>
    <label>Gateway Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LoyaltyTransaction__c/fields/OrderSummary__c.field-meta.xml
<CustomField>
    <fullName>OrderSummary__c</fullName>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Loyatly Transactions</relationshipLabel>
    <relationshipName>LoyatlyTransactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NamedCredential__mdt/NamedCredential__mdt.object-meta.xml
<CustomObject>
    <label>Named Credential</label>
    <pluralLabel>Named Credentials</pluralLabel>
</CustomObject>

force-app/main/default/objects/NamedCredential__mdt/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NamedCredential__mdt/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LOY/YotpoService.cls
public class YotpoService implements Database.Batchable<SObject>, Database.AllowsCallouts {
    public static final String GATEWAY_SUCCESS = 'Send: Yotpo sent successfully';
	public static final String GATEWAY_FAIL = 'Send: Yotpo failed to send';
	public static String interactionType = '';
    public class Refund {
        public String id;
        public String order_id;
        public Integer total_amount_cents;
        public List<RefundItem> items;
        public String currencyx;
    }

    public class RefundItem {
        public String id;
        public Integer quantity;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, Action__c, Amount__c, OrderSummary__c, OrderSummary__r.OrderNumber FROM LoyaltyTransaction__c WHERE GatewayStatus__c = null');
    }

    public void execute(Database.BatchableContext bc, List<LoyaltyTransaction__c> scope) {
        List<SObject> logs = new List<SObject>();
        NamedCredential__mdt cred = NamedCredential__mdt.getInstance('Yotpo');
        for (LoyaltyTransaction__c s : scope) {
            interactionType = s.Action__c;
            String gatewayMessage = null;
            String errorMessage = null;
            HttpResponse res = null;
            Map<String, Object> req;
            try {
                switch on s.Action__c {
                    // https://loyaltyapi.yotpo.com/reference/create-refund
                    when 'Refund', 'Cancel', 'Discount' {
                        Refund obj = new Refund();
                        obj.id = s.Id;
                        obj.order_id = s.OrderSummary__r.OrderNumber;
                        obj.total_amount_cents = (Integer)(s.Amount__c * 100).round(System.RoundingMode.CEILING);
                        req = new Map<String, Object> {
                            'x-api-key' => cred.ClientId__c,
                            'x-guid' => cred.ClientSecret__c,
                            'method' => 'POST',
                            'endpoint' => '/refunds',
                            'body' => JSON.serializePretty(obj)
                        };
                    }
                }
                res = CloudX.callout('yotpo/api/v2', null, req);
                if (res.getStatusCode() == 201) {
					gatewayMessage = GATEWAY_SUCCESS;
					s.GatewayStatus__c = 'Sent';
                    s.GatewaySentOn__c = Datetime.now();
                } else {
					gatewayMessage = GATEWAY_FAIL;
					s.GatewayStatus__c = 'Failed';
				}
                System.debug(res.getBody());
            } catch (Exception e) {
                gatewayMessage = GATEWAY_FAIL;
                errorMessage = e.getMessage() + '\n' + e.getStackTraceString();
                System.debug(System.LoggingLevel.ERROR, errorMessage);
                s.GatewayStatus__c = 'Failed';
                errorMessage = String.format('Exception Type:  {0},   Error Message:  {1},  LineNumber:  {2}, StackTrace: {3}',
                                                   new Object[] { e.getTypeName() , e.getMessage(), e.getLineNumber(), e.getStackTraceString() });
                insert new GenericGatewayLog__c(InteractionType__c = 'LoyaltyTransaction__c', ErrorMessage__c = errorMessage);
            } finally {
                req.remove('x-api-key');
                req.remove('x-guid');
                logs.add(new LoyaltyGatewayLogBuilder()
                    .interactionType(interactionType)
                    .relatedTo(s.OrderSummary__c)
                    .withRequest(req)
                    .withResponse(res)
                    .withErrorMessage(errorMessage)
                    .withGatewayMessage(gatewayMessage)
                    .build());
            }
        }

        if (!scope.isEmpty()) { Database.update(scope, false); }
        if (!logs.isEmpty()) { insert logs; }
	}

    public void finish(Database.BatchableContext bc) {}
}