force-app/main/default/objects/GenericGatewayLog__c/GenericGatewayLog__c.object-meta.xml
<CustomObject>
    <label>Generic Gateway Log</label>
    <nameField>
        <displayFormat>GE{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Gateway Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GenericGatewayLog__c/fields/InteractionType__c.field-meta.xml
<CustomField>
    <fullName>InteractionType__c</fullName>
    <label>Interaction Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__mdt/Notification__mdt.object-meta.xml
<CustomObject>
    <description>Stores the emails of admins to send email for exception.</description>
    <label>Notification</label>
    <pluralLabel>Notifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/Notification__mdt/fields/Email_addresses__c.field-meta.xml
<CustomField>
    <fullName>Email_addresses__c</fullName>
    <label>Email addresses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification__mdt/fields/Interaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Type__c</fullName>
    <label>Interaction Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OMS/CustomCommonUtilTest.cls
@isTest 
public class CustomCommonUtilTest {
    static final String CLASS_NAME = CustomCommonUtilTest.class.getName();
    
    @isTest
    static void logExceptionTest() {
        Notification__mdt notificaiont = [SELECT Id, Interaction_Type__c, Email_addresses__c FROM Notification__mdt LIMIT 1];
        String className = notificaiont.Interaction_Type__c;
        integer i = 2;
        try {
            i = i/0;
        }
        catch(Exception ex) {
            Test.startTest();
            CustomCommonUtil.logException(className, ex);
            Test.stopTest();
        }
        GenericGatewayLog__c gl = [Select InteractionType__c from GenericGatewayLog__c where InteractionType__c =:ClassName];
        System.assertEquals(className, gl.InteractionType__c);
    }
    
    @isTest
    static void getAccessTokenTest() {
        HttpResponse response = new HttpResponse();
        response.setStatusCode(200);
        response.setStatus('OK');
        response.setBody('{"message": "Success"}');
        System.assertEquals('Success', CustomCommonUtil.getAccessToken(response, 'message'));
    }
    
    @isTest
    static void logCalloutTest() {
        CustomCommonUtil.logCallout('interactionType', 'request', 'response', 200, 'gatewayMessage', 'errorMessage', 'referenceId');
    }

    @isTest
    static void sendEmailTest() {
        Notification__mdt notificaiont = [SELECT Id, Interaction_Type__c, Email_addresses__c FROM Notification__mdt LIMIT 1];
        CustomCommonUtil.sendEmail(notificaiont.Interaction_Type__c, 'Error');
    }

    @isTest
    static void getIdSetTest() {
        Account acc = OmsTestDataFactory.createAccount();
        List<Id> idList = new List<Id>{acc.Id};
        Test.startTest();
        Set<Set<Id>> setOfIdSet = CustomCommonUtil.getIdSet(idList);
        Test.stopTest();
        Assert.isNotNull(setOfIdSet);
    }

    @isTest
    static void updateSObjectAndLogErrosTest() {
        List<Account> accList = new List<Account>{new Account()};
        Test.startTest();
        CustomCommonUtil.updateSObjectAndLogErros(accList, CLASS_NAME);
        Test.stopTest();
        GenericGatewayLog__c log = [SELECT Id, InteractionType__c  FROM GenericGatewayLog__c  WHERE InteractionType__c = :CLASS_NAME];
        Assert.areEqual(CLASS_NAME, log.InteractionType__c);
    }
    
    @isTest
    static void getLogObjTest() {
        GenericGatewayLog__c log = CustomCommonUtil.getLogObj(
            'interactionType', 'request', 'response', 
            200, 'gatewayMessage', 'errorMessage', 'referenceId'
        );
        Assert.isNotNull(log);
    }
}