force-app/main/default/objects/GenericGatewayLog__c/GenericGatewayLog__c.object-meta.xml
<CustomObject>
    <label>Generic Gateway Log</label>
    <nameField>
        <displayFormat>GE{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Gateway Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GenericGatewayLog__c/fields/GatewayMessage__c.field-meta.xml
<CustomField>
    <fullName>GatewayMessage__c</fullName>
    <label>Gateway Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericGatewayLog__c/fields/InteractionType__c.field-meta.xml
<CustomField>
    <fullName>InteractionType__c</fullName>
    <label>Interaction Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericGatewayLog__c/fields/Object_Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Object_Reference_Id__c</fullName>
    <description>Captures the object reference Id</description>
    <inlineHelpText>Captures the object reference Id</inlineHelpText>
    <label>Object Reference Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GenericGatewayLog__c/fields/ResultCode__c.field-meta.xml
<CustomField>
    <fullName>ResultCode__c</fullName>
    <label>Result Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__mdt/Notification__mdt.object-meta.xml
<CustomObject>
    <description>Stores the emails of admins to send email for exception.</description>
    <label>Notification</label>
    <pluralLabel>Notifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/Notification__mdt/fields/Email_addresses__c.field-meta.xml
<CustomField>
    <fullName>Email_addresses__c</fullName>
    <label>Email addresses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification__mdt/fields/Interaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Type__c</fullName>
    <label>Interaction Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OMS/CustomCommonUtil.cls
public class CustomCommonUtil {
    
    public static void logException(String interactionType, Exception ex) {
        String errorMessage = 'Exception Type: ' + ex.getTypeName() + ', Error Message: ' + ex.getMessage() + ', LineNumber: ' + ex.getLineNumber() + ', StackTrace: ' + ex.getStackTraceString();
        insert new GenericGatewayLog__c(InteractionType__c = interactionType, ErrorMessage__c = errorMessage);
        //sendEmail(interactionType, errorMessage);
    }
    
    public static String getAccessToken(HttpResponse res, String key) {
        String accessToken;
        if (res.getStatusCode() == 200) {
            Map<String, Object> responseMap = (Map<String, Object>)System.JSON.deserializeUntyped(res.getBody());
            if (responseMap.containsKey(key)) {
                accessToken = (String)responseMap.get(key);
            }
        }
        return accessToken;
    }
    public static void sendEmail(String interactionType, String errorMessage) {
        List<Notification__mdt> notificationList = [SELECT Id, Interaction_Type__c, Email_addresses__c FROM Notification__mdt WHERE Interaction_Type__c = :interactionType];
        if (!notificationList.isEmpty()) {
            for (Notification__mdt notification : notificationList) {
                List<String> emailIds = notification.Email_addresses__c.split(',');
                if (!emailIds.isEmpty()) {
                    Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
                    msg.setSubject('Exception from ' + interactionType);
                    msg.setToAddresses(emailIds);
                    msg.setPlainTextBody(errorMessage);
                    Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{msg});
                }
            }
        }
    }

    public static void logCallout(String interactionType, String request, String response, Integer statusCode, String gatewayMessage, String errorMessage, String referenceId) {
        insert new GenericGatewayLog__c(InteractionType__c = interactionType, Request__c = request, 
                                        Response__c = response, ResultCode__c = statusCode, 
                                        GatewayMessage__c = gatewayMessage, ErrorMessage__c = errorMessage, 
                                        Object_Reference_Id__c = referenceId);
    }

    //Breaks the list of ids into 10 thousand separate set
    public static Set<Set<Id>> getIdSet(List<Id> idList) {
        Set<Set<Id>> setOfIdSet = new Set<Set<Id>>();
        if (!idList.isEmpty()) {
            Integer sObjSize = idList.size();
            Integer maxRecords = 10000;
            Integer outerCount = Integer.valueOf(Math.ceil(Decimal.valueOf(sObjSize) / Decimal.valueOf(maxRecords)));
            Integer innerCount = outerCount == 1 ? sObjSize : 9999;
            Integer j = 0;
            for (Integer i = 1; i <= outerCount; i++) {
                Set<Id> idSet = new Set<Id>();
                for (; j <= innerCount && j < sObjSize; j++) {
                    idSet.add(idList.get(j));
                }
                setOfIdSet.add(idSet);
                j = innerCount + 1;
                innercount = j + 9999;
            }
        }
        return setOfIdSet;
    }

    public static void logDmlException(Database.SaveResult[] srList, String interactionType) {
        String errorMessage;
        List<String> errorList = new List<String>();
        for (Database.SaveResult sr : srList) {
            if (!sr.isSuccess()) {
                for (Database.Error err : sr.getErrors()) {
                    errorMessage = err.getMessage() + ' and the fields that are affected this error: ' + err.getFields();
                    errorList.add(errorMessage);
                }
            }
        }
        if (!errorList.isEmpty()) {
            insert new GenericGatewayLog__c(InteractionType__c = interactionType, ErrorMessage__c = errorList.toString());
        }
    }

    public static void updateSObjectAndLogErros(sObject[] recordsToUpdate, String interactionType) {
        Database.SaveResult[] srList = Database.update(recordsToUpdate, false);
        logDmlException(srList, interactionType);
    }

    public static GenericGatewayLog__c getLogObj(String interactionType, String request, String response, Integer statusCode, String gatewayMessage, String errorMessage, String referenceId) {
        return new GenericGatewayLog__c(
            InteractionType__c = interactionType, Request__c = request, Response__c = response, 
            ResultCode__c = statusCode, GatewayMessage__c = gatewayMessage, 
            ErrorMessage__c = errorMessage, Object_Reference_Id__c = referenceId);
    }
}