force-app/main/default/objects/OmsHistoricalProcessingError__c/OmsHistoricalProcessingError__c.object-meta.xml
<CustomObject>
    <label>OmsHistoricalProcessingError</label>
    <nameField>
        <displayFormat>OH-{0000000}</displayFormat>
        <label>OmsHistoricalProcessingError Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OmsHistoricalProcessingErrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OmsHistoricalProcessingError__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error_Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OmsHistoricalProcessingError__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderID</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>OmsHistoricalProcessingErrors</relationshipLabel>
    <relationshipName>OmsHistoricalProcessingErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/HistoricalProcessingStatus__c.field-meta.xml
<CustomField>
    <fullName>HistoricalProcessingStatus__c</fullName>
    <label>HistoricalProcessingStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NotProcessed</fullName>
                <default>true</default>
                <label>NotProcessed</label>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/IsHistorical__c.field-meta.xml
<CustomField>
    <fullName>IsHistorical__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Historical</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OMS/OmsBatchableApiOrderSummaryCreatorTest.cls
@isTest
public class OmsBatchableApiOrderSummaryCreatorTest {
    @IsTest(SeeAllData=true)
    static void testOmsBatchableApiOrderSummaryCreator() {
    Order orderData = OmsTestDataFactory.createRecordsforOrderSummaryCreation();
        OrderData.IsHistorical__c = true;
        update orderData;
        system.debug('orderData :'+orderData);
        Test.startTest();
        Database.executeBatch(new OmsBatchableApiOrderSummaryCreator(), 2000);
        Test.stopTest();
        Order oredrrecord = [SELECT Id, HistoricalProcessingStatus__c, CreatedDate FROM Order where id =: orderData.Id];
        system.assertEquals('Processed',oredrrecord.HistoricalProcessingStatus__c);
    }
    @IsTest(SeeAllData=true)
    static void testOmsBatchableApiOrderSummaryforerror() {
        String salesChannelName = 'Viviscal';
        Id pricebookId = [SELECT Id, Name, IsDeleted, CurrencyIsoCode, CreatedDate FROM Pricebook2 where name = 'Standard Price Book'].Id;
 		Id saleschannelId =  [SELECT Id, IsDeleted, OwnerId, SalesChannelName, CurrencyIsoCode, CreatedDate, CreatedById FROM SalesChannel where SalesChannelName =:salesChannelName].Id;
        Account acc = new Account();
    	acc.Name = 'Test Account';
        acc.Business_Unit__c = 'AE';
    	insert acc;
        
    	Order testOrder = new Order();
        testOrder.Name = 'testOrder1234';
        testOrder.Status = 'Draft';
        testOrder.OrderReferenceNumber = 'testOrder1234cv';
        testOrder.EffectiveDate = system.today();
        testOrder.AccountId = acc.id;
        testOrder.Pricebook2Id =  pricebookId;
      	testOrder.SalesChannelId=saleschannelId;
        testOrder.IsHistorical__c = True;
      	insert testOrder;
        
        Product2 testProduct = new Product2();
        String sku = 'Normal Product ' + Integer.valueof((Math.random() * 1000));
        testProduct.Name = 'Test Product';
        testProduct.Description='Test Product Entry 1';
        testProduct.productCode = sku;
        testProduct.isActive = true;
        testProduct.StockKeepingUnit = sku;
        insert testProduct;
        
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = pricebookId;
        standardPrice.Product2Id = testProduct.Id;
        standardPrice.UnitPrice = 200;
        standardPrice.IsActive = true;
        standardPrice.UseStandardPrice = false;
        insert standardPrice;
        
		OrderItem orderItemProduct = new OrderItem();
        orderItemProduct.OrderId = testOrder.Id;
        orderItemProduct.Quantity = 1;
        orderItemProduct.UnitPrice = 200;
        orderItemProduct.TotalLineAmount = 200;
        orderItemProduct.Product2id = testProduct.id;
        orderItemProduct.PricebookEntryId=standardPrice.id;
        orderItemProduct.Type = 'Order Product';
        Insert orderItemProduct;
        Test.startTest();
        Database.executeBatch(new OmsBatchableApiOrderSummaryCreator());
        Test.stopTest();
        OmsHistoricalProcessingError__c error = [SELECT Id, OrderID__c, Error_Message__c FROM OmsHistoricalProcessingError__c where OrderID__c =: testOrder.Id  ];
        system.assertEquals(testOrder.Id, error.OrderID__c);
    }
}