force-app/main/default/objects/CreditMemo/fields/IsExportedToSAP__c.field-meta.xml
<CustomField>
    <fullName>IsExportedToSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Exported To SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Refund__c/Custom_Refund__c.object-meta.xml
<CustomObject>
    <label>Custom Refund</label>
    <nameField>
        <label>Custom Refund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Refunds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Refund__c/fields/IsCancelledRefund__c.field-meta.xml
<CustomField>
    <fullName>IsCancelledRefund__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field returns boolean value, returns true if the order has give 100 percent discount before the fulfillment of the order</description>
    <label>Is Cancelled Refund</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Refund__c/fields/IsExportedToSAP__c.field-meta.xml
<CustomField>
    <fullName>IsExportedToSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Exported To SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Refund__c/fields/Reference_ChangeOrder__c.field-meta.xml
<CustomField>
    <fullName>Reference_ChangeOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference ChangeOrder</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Custom Refunds</relationshipLabel>
    <relationshipName>Custom_Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Refund__c/fields/Reference_Order_Payment_Summary__c.field-meta.xml
<CustomField>
    <fullName>Reference_Order_Payment_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Payment Summary</label>
    <referenceTo>OrderPaymentSummary</referenceTo>
    <relationshipLabel>Custom Refunds</relationshipLabel>
    <relationshipName>Custom_Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Refund__c/fields/Reference_Refund__c.field-meta.xml
<CustomField>
    <fullName>Reference_Refund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Refund</label>
    <referenceTo>Refund</referenceTo>
    <relationshipLabel>Custom Refunds</relationshipLabel>
    <relationshipName>Custom_Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderPaymentSummary/fields/IsExportedToSAP__c.field-meta.xml
<CustomField>
    <fullName>IsExportedToSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Keep track of records whether exported to sap or not.</description>
    <label>IsExportedToSAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ERP/SapRefundExportJobTest.cls
@isTest 
public class SapRefundExportJobTest {
    static List<String> foIds = new List<String>();
    @IsTest(SeeAllData=true)
    static void testSapRefundExportJobTest() {
        try {
            String osId = OmsTestDataFactory.createOrderSummaryCA();
            String fulfillmentOrderIds = OmsTestDataFactory.createFulfillmentOrder(osId, 'Warehouse');
            foIds.add(fulfillmentOrderIds);
            FulfillmentOrder foList = [SELECT Id, OrderSummaryId, InvoiceId FROM FulfillmentOrder WHERE Id IN :foIds limit 1];
            foList.Status = 'Fulfilled';
            update foList;
            //FulfillmentOrder invoice = OmsTestDataFactory.invoiceFulfillmentOrder(foList);
            Order changeOrderId = OmsTestDataFactory.createOrderChange(osId, foList, 'Return');
            CreditMemo creditmemorecord = OmsTestDataFactory.createCreditMemo(osId, changeOrderId.Id);
			OrderPaymentSummary ops  = [SELECT Id, CreatedDate, OrderSummaryId FROM OrderPaymentSummary where OrderSummaryId =: osId ];
            
            Refund ref = new Refund ();
            ref.GatewayRefNumber = 'cmVmdW5kXzR3NXNiNWI1'; 
            ref.CurrencyIsoCode = 'USD';
            ref.Amount = 10;
            ref.Type = 'Referenced';
            ref.Status = 'processed';
            ref.ProcessingMode = 'External';
            ref.OrderPaymentSummaryId = ops.Id;
            insert ref; 
           
            Custom_Refund__c cr = new Custom_Refund__c();
            cr.Reference_Refund__c = ref.Id;
            cr.Reference_ChangeOrder__c = changeOrderId.Id;
            cr.Reference_Order_Payment_Summary__c = ops.Id;
            cr.IsCancelledRefund__c = false;
            cr.IsExportedToSAP__c = false;
            insert cr;
            
            Test.startTest();
            Database.executeBatch(new SapRefundExportJob());
            Test.stopTest();
            Custom_Refund__c crc = [SELECT Id, Reference_Refund__c, IsExportedToSAP__c, IsCancelledRefund__c, Reference_ChangeOrder__c, Reference_Order_Payment_Summary__c FROM Custom_Refund__c where Reference_Refund__c =: ref.Id ];
            system.assertEquals(true, crc.IsExportedToSAP__c);
        } 
        catch (Exception e) {
            System.debug('Exception occoured' + e.getMessage());
        } 
    }
   
    @IsTest(SeeAllData=true)
    static void testSapRefundExportJobScheduler() {
        Test.StartTest();
        String CRON = '0 0 23 * * ?';
        system.schedule('testSapRefundExportJobScheduler', CRON, new SapRefundExportJobScheduler());
        Test.stopTest();
    }
}