force-app/main/default/objects/Custom_Refund__c/Custom_Refund__c.object-meta.xml
<CustomObject>
    <label>Custom Refund</label>
    <nameField>
        <label>Custom Refund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Refunds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Refund__c/fields/IsCancelledRefund__c.field-meta.xml
<CustomField>
    <fullName>IsCancelledRefund__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field returns boolean value, returns true if the order has give 100 percent discount before the fulfillment of the order</description>
    <label>Is Cancelled Refund</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Refund__c/fields/IsExportedToSAP__c.field-meta.xml
<CustomField>
    <fullName>IsExportedToSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Exported To SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Refund__c/fields/Reference_ChangeOrder__c.field-meta.xml
<CustomField>
    <fullName>Reference_ChangeOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference ChangeOrder</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Custom Refunds</relationshipLabel>
    <relationshipName>Custom_Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Refund__c/fields/Reference_Order_Payment_Summary__c.field-meta.xml
<CustomField>
    <fullName>Reference_Order_Payment_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Payment Summary</label>
    <referenceTo>OrderPaymentSummary</referenceTo>
    <relationshipLabel>Custom Refunds</relationshipLabel>
    <relationshipName>Custom_Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderPaymentSummary/fields/IsExportedToSAP__c.field-meta.xml
<CustomField>
    <fullName>IsExportedToSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Keep track of records whether exported to sap or not.</description>
    <label>IsExportedToSAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Refund/fields/IsLinkedToCustomRefund__c.field-meta.xml
<CustomField>
    <fullName>IsLinkedToCustomRefund__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field returns boolean value, if it is linked to custom refund record it is true or else false</description>
    <inlineHelpText>Is Linked To Custom Refund record</inlineHelpText>
    <label>Is Linked To Custom Refund</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ERP/CaptureAsynRefundsTest.cls
@IsTest
public class CaptureAsynRefundsTest {
    
    @IsTest(SeeAllData=true)
    static void captureAsynRefundsTest() {
    	String osId = OmsTestDataFactory.createOrderSummaryUS();
        String foIds = OmsTestDataFactory.createFulfillmentOrder(osId, 'Warehouse');
        List<FulfillmentOrder> foList = [SELECT Id, OrderSummaryId FROM FulfillmentOrder WHERE Id =: foIds];
        for(FulfillmentOrder fo: foList) {
            OmsTestDataFactory.invoiceFulfillmentOrder(fo);
        }
        String roId = OmsTestDataFactory.createRMAReturnOrder(osId);
        String changeOrderId = OmsTestDataFactory.RetunRMAReturnOrder(roId);
        Order o = [SELECT Id, GrandTotalAmount from Order WHERE Id =:changeOrderId];
        OrderPaymentSummary ops  = [SELECT Id, CreatedDate, OrderSummaryId FROM OrderPaymentSummary where OrderSummaryId =: osId];
        Refund ref = new Refund ();
        ref.GatewayRefNumber = 'cmVmdW5kXzR3NXNiNWI1'; 
        ref.CurrencyIsoCode = 'USD';
        ref.Amount = Math.abs(o.GrandTotalAmount);
        ref.Type = 'Referenced';
        ref.Status = 'processed';
        ref.ProcessingMode = 'External';
        ref.OrderPaymentSummaryId = ops.Id;
        insert ref; 
        Custom_Refund__c cr = new Custom_Refund__c();
        cr.Reference_ChangeOrder__c = changeOrderId;
        cr.Reference_Order_Payment_Summary__c = ops.Id;
        cr.IsCancelledRefund__c = false;
        cr.IsExportedToSAP__c = false;
        insert cr;
        Test.startTest();
        System.schedule('CaptureAsynRefunds', '0 0 * * * ?', new CaptureAsynRefunds());
        Test.stopTest();
        Refund rFund = [SELECT Id, 	IsLinkedToCustomRefund__c FROM Refund WHERE Id =:ref.Id];
        System.assertEquals(true, rFund.IsLinkedToCustomRefund__c);
    }
}