force-app/main/default/objects/FulfillmentOrder/fields/AmwareShipDate__c.field-meta.xml
<CustomField>
    <fullName>AmwareShipDate__c</fullName>
    <description>It is used to store the Ship Date from Amware</description>
    <inlineHelpText>Ship Date from Amware</inlineHelpText>
    <label>Amware Ship Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OrderItemSummary/fields/sfcc_BundleProductGUID__c.field-meta.xml
<CustomField>
    <fullName>sfcc_BundleProductGUID__c</fullName>
    <description>This field stores Bundle Product GUID from SFCC</description>
    <inlineHelpText>Bundle Product GUID from SFCC</inlineHelpText>
    <label>SFCC Bundle Product GUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItemSummary/fields/sfcc_SAPMaterialCode__c.field-meta.xml
<CustomField>
    <fullName>sfcc_SAPMaterialCode__c</fullName>
    <description>Its SAP Material Code that we will be receiving from SFCC</description>
    <inlineHelpText>SAP Material Code from SFCC</inlineHelpText>
    <label>SAP Material SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/AmwareShipDate__c.field-meta.xml
<CustomField>
    <fullName>AmwareShipDate__c</fullName>
    <description>It is used to store the Ship Date from Amware</description>
    <inlineHelpText>Ship Date from Amware</inlineHelpText>
    <label>Amware Ship Date</label>
    <type>DateTime</type>
</CustomField>

not-used/classes/MockUtility.cls
public class MockUtility {
    
    public static void updateFoStatusAndCreateShipment(List<String> foIds) {
        DateTime TodayDate =date.today();
        List<Shipment> shipmentList = new List<Shipment>();
        Set<Id> osIds = new Set<Id>();
        List<FulfillmentOrder> fulfillmentOrders = [SELECT Id, FulfilledToName, OrderSummaryId, Status,
            (SELECT Id, Quantity, Type, OrderItemSummaryId, OrderItemSummary.sfcc_BundleProductGUID__c, 
      		OrderItemSummary.sfcc_SAPMaterialCode__c, OrderItemSummary.ProductCode  
      		FROM FulfillmentOrderLineItems WHERE Type = 'Order Product' ORDER BY  
      		OrderItemSummary.sfcc_BundleProductGUID__c ASC)
     		FROM FulfillmentOrder WHERE Id IN :foIds];
        for (FulfillmentOrder fo : fulfillmentOrders) {
            fo.Status = 'FULFILLED';
            shipmentList.add(new Shipment(FulfillmentOrderId = fo.Id, ShipToName = fo.FulfilledToName,
				OrderSummaryId = fo.OrderSummaryId, AmwareShipDate__c = TodayDate,
                TrackingNumber = 'TO-' + fo.Id, Description = 'Shipped'));
            osIds.add(fo.OrderSummaryId);
        }
        if(!fulfillmentOrders.isEmpty()) {
            update fulfillmentOrders;
        }
        if (!shipmentList.isEmpty()){
            insert shipmentList;
        }
        if(!osIds.isEmpty()) {
            updateOrderSummaryStatus(osIds);
        }
    }
    
    public static void updateReturnOrders(List<String> roIds) {
        List<ReturnOrder> roList = [SELECT Id, Status, (SELECT Id, QuantityExpected, QuantityReceived FROM ReturnOrderLineItems) FROM ReturnOrder WHERE Id IN :roIds];
        List<ReturnOrderLineItem> roLineListToUpdate = new List<ReturnOrderLineItem>();
        for(ReturnOrder ro: roList) {
            for(ReturnOrderLineItem roLine: ro.ReturnOrderLineItems) {
                roLine.QuantityReceived = roLine.QuantityExpected;
                roLineListToUpdate.add(roLine);
            }
            ro.Status = 'Refund_Initiated';
        }
        if(!roLineListToUpdate.isEmpty()) {
            update roLineListToUpdate;
        }
        if(!roList.isEmpty()) {
            update roList;
        }
    }
    
    public static void updateOrderSummaryStatus(Set<Id> osIds){
        List<OrderSummary> osList = [SELECT Id, Status FROM OrderSummary WHERE Id IN :osIds];
        for(OrderSummary os : osList) {
            os.Status = 'FULFILLED';
        }
        update osList;
    }
}