force-app/main/default/objects/PositiveOrderStatus__c/PositiveOrderStatus__c.object-meta.xml
<CustomObject>
    <label>Positive Order Status</label>
    <nameField>
        <label>Positive Order Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positive Order Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PositiveOrderStatus__c/fields/FulfillmentOrder__c.field-meta.xml
<CustomField>
    <fullName>FulfillmentOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fulfillment Order</label>
    <referenceTo>FulfillmentOrder</referenceTo>
    <relationshipLabel>Positive Order Statuses</relationshipLabel>
    <relationshipName>Positive_Order_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PositiveOrderStatus__c/fields/IsImported__c.field-meta.xml
<CustomField>
    <fullName>IsImported__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is imported from Positive Fulfillment Service</description>
    <inlineHelpText>Is imported from Positive Fulfillment Service(PFS)</inlineHelpText>
    <label>Is Imported</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PositiveOrderStatus__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <description>Positive Fulfillment Service Order Id</description>
    <inlineHelpText>PFS Order Id</inlineHelpText>
    <label>Order Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WMS/Positive/PositiveOrderDetailsStatusImportJobTest.cls
@isTest
public class PositiveOrderDetailsStatusImportJobTest {
    static final String AUTH_RESPONSE = '{"access_token":"accessToken"}';
    static final String FULFILLED = 'Fulfilled';
	
    @isTest(SeeAllData=true)
    static void positiveOrderDetailsStatusImportJobTest() {
        FulfillmentOrder fo;
        String osId = OmsTestDataFactory.createOrderSummaryCA();
        String foId = OmsTestDataFactory.createFulfillmentOrder(osId, 'Warehouse');
        String positiveOrderStatus = PositiveMockResponseTest.getOrderStatusResponse(foId);
        String orderId = '12345';
        PositiveOrderStatus__c pos = new PositiveOrderStatus__c(FulfillmentOrder__c = foId, OrderId__c = orderId, IsImported__c = false);
        insert pos;
        Test.setMock(HttpCalloutMock.class, new HttpCalloutServiceMultiMock(new Map<String, HttpCalloutServiceMock> {
            'callout:PositiveAuth/oauth/token'  => new HttpCalloutServiceMock(200, AUTH_RESPONSE),
            'callout:PositiveAPI/v0/order/' + orderId => new HttpCalloutServiceMock(200, positiveOrderStatus)}));
        Test.startTest();
        Database.executeBatch(new PositiveOrderDetailsStatusImportJob());
        Test.stopTest();
        fo = [SELECT Id, Status FROM FulfillmentOrder WHERE Id = :foId];
        System.assertEquals(FULFILLED, fo.Status);
        pos = [SELECT Id, IsImported__c FROM PositiveOrderStatus__c WHERE Id = :pos.Id];
        System.assertEquals(true, pos.IsImported__c);
    }
}