force-app/main/default/objects/LoyaltyTransaction__c/LoyaltyTransaction__c.object-meta.xml
<CustomObject>
    <label>Loyalty Transaction</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Loyalty ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LoyaltyTransaction__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Capture</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LoyaltyTransaction__c/fields/GatewayStatus__c.field-meta.xml
<CustomField>
    <fullName>GatewayStatus__c</fullName>
    <label>Gateway Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LoyaltyTransaction__c/fields/OrderSummary__c.field-meta.xml
<CustomField>
    <fullName>OrderSummary__c</fullName>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Loyatly Transactions</relationshipLabel>
    <relationshipName>LoyatlyTransactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LOY/YotpoServiceTest.cls
@isTest
public class YotpoServiceTest {
    static OrderSummary setup() {
        OmsOrderDataFactory.get.preamble();
        OrderSummary orderSummary = OmsOrderDataFactory.get.createOrderSummary('Standard');
        return orderSummary;
    }

    @isTest(seeAllData=true)
    static void shouldExecuteBatch() {
        //OrderSummary orderSummary = setup();
        String osId = OmsTestDataFactory.createOrderSummaryUS();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutServiceMock(201, '{}'));
        LoyaltyTransactionTriggerHandler.disabled = true;
        Test.startTest();
        LoyaltyTransaction__c t = new LoyaltyTransaction__c(Action__c = 'Refund', Amount__c = 1, OrderSummary__c = osId);
        insert t;
        Database.executeBatch(new YotpoService(), 2000);
        Test.stopTest();
        LoyaltyTransaction__c actual = [SELECT GatewayStatus__c FROM LoyaltyTransaction__c WHERE Id = :t.Id];
        System.assertEquals('Sent', actual.GatewayStatus__c);
    }

    @isTest(seeAllData=true)
    public static void shouldTrigger() {
        //OrderSummary orderSummary = setup();
        String osId = OmsTestDataFactory.createOrderSummaryUS();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutServiceMock(201, '{}'));
        LoyaltyTransactionTriggerHandler.disabled = false;
        Test.startTest();
        LoyaltyTransaction__c t = new LoyaltyTransaction__c(Action__c = 'Refund', Amount__c = 1, OrderSummary__c = osId);
        insert t;
        Test.stopTest();
        LoyaltyTransaction__c actual = [SELECT GatewayStatus__c FROM LoyaltyTransaction__c WHERE Id = :t.Id];
        System.assertEquals('Sent', actual.GatewayStatus__c);
    }
}