force-app/main/default/objects/LoyaltyTransaction__c/LoyaltyTransaction__c.object-meta.xml
<CustomObject>
    <label>Loyalty Transaction</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Loyalty ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LoyaltyTransaction__c/fields/GatewayStatus__c.field-meta.xml
<CustomField>
    <fullName>GatewayStatus__c</fullName>
    <label>Gateway Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LOY/LoyaltyTransactionTriggerHandler.cls
public class LoyaltyTransactionTriggerHandler extends TriggerHandlerX {
    public static Boolean disabled = false;

    public override void afterInsert() { 
        execute((List<LoyaltyTransaction__c>)Trigger.new);
    }
    
    public override void afterUpdate() { 
        execute((List<LoyaltyTransaction__c>)Trigger.new);
    }

    public static void execute(List<LoyaltyTransaction__c> scope) {
        if (disabled) { return; }
        for (LoyaltyTransaction__c s : scope) {
            if (s.GatewayStatus__c == null) {
                Database.executeBatch(new YotpoService());
                return;
            }
        }
    }
}