force-app/main/default/objects/OrderSummary/fields/PF_Order_ID__c.field-meta.xml
<CustomField>
    <fullName>PF_Order_ID__c</fullName>
    <description>Store the ID received from Positive services</description>
    <label>PF_Order_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderSummary/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>To count the no of API calls for particular order to Positive fulfillment</description>
    <label>Retry_Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WMS/Positive/PositiveOrderDetailsStatusImportTestV2.cls
@isTest
public class PositiveOrderDetailsStatusImportTestV2 {
    static final String AUTH_RESPONSE = '{"access_token":"accessToken"}';
    static final String FULFILLED = 'Fulfilled';
	
    @isTest(SeeAllData=true)
    static void positiveOrderDetailsStatusImportTest() {
        FulfillmentOrder fo;
        String osId = OmsTestDataFactory.createOrderSummaryCA();
        String foId = OmsTestDataFactory.createFulfillmentOrder(osId, 'Warehouse');
        OrderSummary os = [SELECT Id, PF_Order_ID__c, status, ordernumber, Retry_Count__c FROM ordersummary WHERE Id = :osId limit 1];
        os.PF_Order_ID__c = '2e59c478-699a-4395-b238-6e46875dtest';
        os.status = 'Waiting to Fulfill';
        os.Retry_Count__c = 2;
        update os;
        String pfId = os.PF_Order_ID__c;
        String positiveOrderStatus = PositiveMockResponseTest.getOrderStatusResponseV2(pfId);
        String orderId = pfId;
        Test.setMock(HttpCalloutMock.class, new HttpCalloutServiceMultiMock(new Map<String, HttpCalloutServiceMock> {
            'callout:PositiveAuth/oauth/token'  => new HttpCalloutServiceMock(200, AUTH_RESPONSE),
            'callout:PositiveAPI/v0/order/' + orderId => new HttpCalloutServiceMock(200, positiveOrderStatus)}));
        Test.startTest();
        Database.executeBatch(new PositiveOrderDetailsStatusImportJobV2());
        Test.stopTest();
        fo = [SELECT Id, Status FROM FulfillmentOrder WHERE Id = :foId];
        System.assertEquals(FULFILLED, fo.Status);
    }
}